### ISSUE TITLE
Wait for Deployment via API

### ISSUE THREAD

**Issue by revett** [vidsy/tutum-startup#1]
### Problem

The script currently relies on a `sleep` to wait for the node to finish deploying in Tutum.

### Solution

The `tutum-cli` gives the state of the deployment via:

```
tutum node inspect $TUTUM_UUID
```

This can be used to get a more accurate sleep duration.

**Comment by amegianeg** [comment]
You can use the _non_-documented (blame us! :( ) `--sync` option for this to wait for the node to be deployed
It is barely the same if you take a look at the code
https://github.com/tutumcloud/cli/blob/ed11fbc0bdc3632001abca881ff812b4f6395ccc/tutumcli/utils.py#L400
