### ISSUE TITLE
Get Tutum creds from S3

### ISSUE THREAD

**Issue by revett** [vidsy/tutum-startup#2]
### Problem

Currently the Tutum API credentials are within the script itself, which will end up on Github and thus won't be secure.

### Solution

- Save the credentials in a private S3 bucket.
- Use the `aws-cli` to retrieve them.

**Comment by jskeates** [comment]
If your EC2 Instance Role has permission to access the S3 bucket, a good way to do this might be with the streaming option in `aws s3 cp`:
```bash
S3_BUCKET=tutum_staging_credentials
export TUTUM_USER=$(aws s3 cp s3://${S3_BUCKET}/tutum_user -)
export TUTUM_APIKEY=$(aws s3 cp s3://${S3_BUCKET}/tutum_apikey -)
```
